name             "shunit2"
maintainer       "Kei Hino"
maintainer_email "kei.hino+github@gmail.com"
license          "Apache 2.0"
description      "shUnit2 install cookbook."
long_description "Please refer to README.md."
version          "0.1.0"

supports "redhat"
supports "centos"
supports "fedora"
supports "scientific"
